routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::redirect('/home','/quiz')->name('home');

Route::resources([
    '/quiz' => 'Maker\QuizController',
    '/information' => 'Maker\InformationController'
]);

Route::get('/start/{quiz:slug}','QuizController@start')
    ->name('quiz.start');

Route::post('/next','QuizController@next')
    ->name('quiz.next');

Route::get('/reset','QuizController@reset')
    ->name('quiz.reset');

Auth::routes();

app/Quiz.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Quiz extends Model
{
    protected $fillable =[
        'name','slug','user_id'
    ];

    public function information(){
        return $this->hasMany(Information::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Maker/InformationController.php
<?php

namespace App\Http\Controllers\Maker;

use App\Http\Controllers\Controller;
use App\Information;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class InformationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(Information::class,'information');
    }
    /**
     * Display a listing of the resource.
     *
     *
     */
    public function index()
    {
        return redirect()->back();
    }

    /**
     * Show the form for creating a new resource.
     *
     *
     */
    public function create()
    {
        $data = User::find(auth()->id())->quizzes;
        return view('Maker.Information.create',[
            'data' => $data
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     */
    public function store(Request $request)
    {
        $this->validateRequest($request->all())->validate();

        $path = $request->file('file')->store('image');

        $path = Str::of($path)->replace('image','/storage/image');

        Information::create([
            'name' => $request->name,
            'picture_url' => $path,
            'quiz_id' => $request->quiz
        ]);
        session()->flash('success',true);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Information  $information
     *
     */
    public function show(Information $information)
    {
        return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Information  $information
     *
     */
    public function edit(Information $information)
    {
        return redirect()->back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Information  $information
     *
     */
    public function update(Request $request, Information $information)
    {
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Information  $information
     *
     */
    public function destroy(Information $information)
    {
        $path = Str::of($information->picture_url)->replace('/storage/','');

        $message = Storage::disk('public')->delete($path);

        $information->delete();

        session()->flash('success', $message);

        return redirect()->back();
    }

    public function validateRequest(Array $data){
        return Validator::make($data,[
            'name' => 'required|string',
            'quiz' => 'required|numeric',
            'file' => 'required|mimes:jpeg,bmp,png'
        ]);
    }
}

app/Http/Controllers/Maker/QuizController.php
<?php

namespace App\Http\Controllers\Maker;

use App\Http\Controllers\Controller;
use App\Quiz;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class QuizController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(Quiz::class,'quiz');
    }

    /**
     * Display a listing of the resource.
     *
     *
     */
    public function index()
    {
        $data = User::find(auth()->id())->quizzes()->get();
        return view('Maker.Quiz.index',[
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     *
     */
    public function create()
    {
        return view('Maker.Quiz.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     */
    public function store(Request $request)
    {
        $this->validateRequest($request->all())->validate();

        $slug = Str::of($request->name.auth()->user()->name.'-'.now())->slug();

        Quiz::create([
           'name' => $request->name,
           'user_id' => auth()->id(),
           'slug' =>  $slug
        ]);

        return redirect()->route('quiz.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Quiz  $quiz
     *
     */
    public function show(Quiz $quiz)
    {
        $data = $quiz->information;
        return view('Maker.Quiz.view',[
            'data' => $data,
            'name' => $quiz->name,
            'slug' => $quiz->slug
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Quiz  $quiz
     *
     */
    public function edit(Quiz $quiz)
    {
        return view('Maker.Quiz.edit',[
            'data' => $quiz
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Quiz  $quiz
     *
     */
    public function update(Request $request, Quiz $quiz)
    {
        $this->validateRequest($request->all())->validate();

        $slug = Str::of($request->name.auth()->user()->name.'-'.now())->slug();

        $quiz->update([
           'name' => $request->name,
           'slug' =>  $slug
        ]);

        return redirect()->route('quiz.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Quiz  $quiz
     *
     */
    public function destroy(Quiz $quiz)
    {
        foreach ($quiz->information() as $information){
            $path = Str::of($information['picture_url'])->replace('/storage/','');

            Storage::disk('public')->delete($path);
        }

        $quiz->information()->delete();

        $quiz->delete();

         return redirect()->back();
    }

    public function validateRequest(Array $data){
        return Validator::make($data,[
            'name' => 'required|string'
        ]);
    }
}

app/Http/Controllers/QuizController.php
<?php

namespace App\Http\Controllers;

use App\Quiz;
use Illuminate\Http\Request;

class QuizController extends Controller
{
    public function start(Quiz $quiz){
        $i = -1;
        if (session('stage') == null){
            $data = $quiz->information()->orderByRaw('RAND()')->get();
            foreach ($data as $d){
                $i++;
            }
            session([
                'first' => 0,
                'second' => 1,
                'data' => $data,
                'count' => $i,
                'stage' => true
            ]);
            $i = 0;
        }

        if (session('second') > session('count')){
            $x = array();

            foreach (session('data') as $f){
                $x[$f["id"]] = $f;
            }

            return view('final',[
               'data' => $x[session('final')]
            ]);
        }elseif(session('first') > session('count')){
            $x = array();

            foreach (session('data') as $f){
                $x[$f["id"]] = $f;
            }

            return view('final',[
               'data' => $x[session('final')]
            ]);
        }else{
            return view('quiz',[
                'first' => session('data')[session('first')],
                'second' => session('data')[session('second')],
                'name' => $quiz->name
            ]);
        }
    }

    public function next(Request $request){
        $s = $request->select;
        if ($s == 'first'){

            session([
               'second' => session('second') + 1
            ]);

            if (session('second') <= session('first')){
                session([
                    'second' => session('first') + 1
                ]);
            }

            if (session('second') > session('count')) {
                session([
                    'final' => $request->id
                ]);
            }
        }else {

            session([
                'first' => session('first') + 1
            ]);

            if (session('first') <= session('second')) {
                session([
                    'first' => session('second') + 1
                ]);
            }

            if (session('first') > session('count')) {
                session([
                    'final' => $request->id
                ]);
            }
        }
        return redirect()->back();
    }

    public function reset(){
        session()->forget([
            'first','second','count','data','stage'
        ]);

        return redirect()->back();
    }
}

resources/views/Maker/Quiz/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>add quiz</h1>
        </div>
        <div class="row">
            <form action="{{route('quiz.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">quiz name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter name">
                </div>
                <button type="submit" class="btn btn-success">create</button>
            </form>
        </div>
    </div>
@endsection

resources/views/Maker/Quiz/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>edit quiz</h1>
        </div>
        <div class="row">
            <form action="{{route('quiz.update',$data->id)}}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">quiz name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" value="{{$data->name}}">
                </div>
                <button type="submit" class="btn btn-success">create</button>
            </form>
        </div>
    </div>
@endsection

resources/views/Maker/Quiz/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>your quizzes</h1>
        </div>
        <div class="row">
            <a href="{{route('quiz.create')}}" class="btn btn-success">create</a>
        </div>
        @foreach($data as $d)
            <div class="row">
                <div class="card w-75 mt-2">
                    <h2 class="card-title">{{$d->name}}</h2>
                    <div class="card-body">
                        <div class="row">
                            <a href="{{route('information.create')}}" class="btn btn-light">add data</a>
                            <a href="{{route('quiz.edit',$d->id)}}" class="btn btn-warning ml-4">edit</a>
                            <a href="{{route('quiz.show',$d->id)}}" class="btn btn-success ml-4">view</a>
                            <form action="{{route('quiz.destroy',$d->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger ml-4">remove</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/Maker/Quiz/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>{{$name}}</h1>
        </div>
        <div class="row">
            <p>
                share link:
                {{route('quiz.start',$slug)}}
            </p>
        </div>
        @if(session('success') == true)
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>card removed!</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        @foreach($data as $d)
            <div class="row">
                <div class="card w-75 mt-2">
                    <h2 class="card-title">{{$d->name}}</h2>
                    <div class="card-body">
                        <img src="{{$d->picture_url}}" alt="{{$d->name}}" style="width: 80%">
                    </div>
                    <div class="card-body">
                        <form action="{{route('information.destroy',$d->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">remove</button>
                        </form>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection